name: outlook build wrappers

on:
  push:
    branches:
      - master
      - "support/**"
      - "feature/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      commitMessage:
        description: Enter the Commit Message
        required: true
env:
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  BRANCH_NAME: ${{ github.ref_name }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  GIT_EMAIL: ${{ secrets.BOT_GITHUB_EMAIL }}
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}


jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: "Setup maven"
        shell: bash
        run: |
          [ -d ${HOME}/.m2/ ] || mkdir -p ${HOME}/.m2/
          cp -v _ci/settings.xml ${HOME}/.m2/ || cp -v .travis.settings.xml ${HOME}/.m2/settings.xml

      - name: "Build and test"
        run: |
            mvn install -DskipTests=true -B -V
            mvn test

  Release:
    runs-on: ubuntu-latest
    if: ${{ ( !contains(github.event.head_commit.message, '[no-release]')  ) && ( github.ref_name == 'master' || startsWith(github.ref_name, 'support/')) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Set up Java"
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: "Setup maven"
        shell: bash
        run: |
          [ -d ${HOME}/.m2/ ] || mkdir -p ${HOME}/.m2/
          cp -v _ci/settings.xml ${HOME}/.m2/ || cp -v .travis.settings.xml ${HOME}/.m2/settings.xml

      - name: "Prepare Staging Deploy"
        run: |
          mvn install -DskipTests=true -B -V
          git checkout -B "$BRANCH_NAME"
          git config user.email "${GIT_EMAIL}"
          mvn --batch-mode -q -DscmCommentPrefix="[maven-release-plugin][skip ci] " -Dusername="${GIT_USERNAME}" -Dpassword="${GIT_PASSWORD}" -DskipTests -Darguments=-DskipTests release:clean release:prepare release:perform